includes: ['/tmp/a', '/tmp/b']
excludes: ['/tmp/a/exclude', '.cvs*']
databases: ['application1_db', 'application2_db']
database_user: root
database_pass: pass
path: '/tmp/backup'
yearly: 2
monthly: 12
weekly: 4
daily: 7
tar_path: '/bin/tar'
mysqldump_path: '/usr/bin/mysqldump'