includes: [ "#tmp_dir#/to_back" ]
excludes: [ "#tmp_dir#/to_back/b", "#tmp_dir#/to_back/c", "*exclude*" ]
databases: ['test']
database_user: root
database_pass: 
path: '#tmp_dir#'
yearly: 1
monthly: 4
weekly: 2
daily: 5
tar_path: '/usr/bin/tar'
mysqldump_path: '/usr/local/bin/mysqldump'