includes: ['/tmp/a', '/tmp/b']
excludes: ['/tmp/a/exclude', '.cvs*']
databases: ['information_schema']
database_user: root
database_pass: pass
path: '/tmp/backup'
yearly: 2
monthly: 12
weekly: 4
daily: 7